ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER joy
IDENTIFIED BY Joy1234
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO joy;
GRANT CREATE TABLE TO joy;
GRANT CREATE VIEW TO joy;
GRANT CREATE SEQUENCE TO joy;
GRANT CREATE PROCEDURE TO joy;
GRANT CREATE TRIGGER TO joy;

EXIT;