-- 한줄 실행 : ctrl + enter
-- 여러줄 한꺼번에 실행 : Alt + X
ALTER SESSION SET CONTAINER = FREEPDB1;

SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS CON_NAME
FROM DUAL;

ALTER SESSION SET CONTAINER = FREEPDB1;

SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS CON_NAME
FROM DUAL;

SELECT TABLESPACE_NAME, CONTENTS, STATUS
FROM DBA_TABLESPACES
ORDER BY TABLESPACE_NAME;

SELECT NAME, VALUE
FROM V$PARAMETER
WHERE NAME = 'db_create_file_dest';

CREATE TABLESPACE USERS
DATAFILE '/opt/oracle/oradata/FREE/FREEPDB1/users01.dbf'
SIZE 100M
AUTOEXTEND ON
NEXT 50M
MAXSIZE 1G;

-- --- 사용을 위한 설정 완료

-- 계정 만들기
CREATE USER joy
IDENTIFIED BY Joy1234
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;


-- 계정 생성 여부 확인
SELECT USERNAME, ACCOUNT_STATUS
FROM DBA_USERS
WHERE USERNAME = 'JOY';

-- 권한 부여
GRANT CREATE SESSION TO joy;
GRANT CREATE TABLE TO joy;
GRANT CREATE VIEW TO joy;
GRANT CREATE SEQUENCE TO joy;
GRANT CREATE PROCEDURE TO joy;
GRANT CREATE TRIGGER TO joy;

-- 권한 부여 한꺼번에 하는 방법
GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE SEQUENCE,
    CREATE PROCEDURE,
    CREATE TRIGGER
TO joy;


-- DB 생성하기
-- 현재 접속 세션의 작업 대상 컨테이너를 FREEPDB1 PDB로 변경한다
ALTER SESSION SET CONTAINER = FREEPDB1;


-- 현재 위치 생성
SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS CON_NAME
FROM DUAL;

--관리자 계정으로 CDB$ROOT에 접속
ALTER SESSION SET CONTAINER = CDB$ROOT;

-- OMF 설정 확인
SELECT VALUE
FROM V$PARAMETER
WHERE NAME = 'db_create_file_dest';

--기존 PDB의 데이터파일 위치를 확인하는 것
SELECT FILE_NAME, TABLESPACE_NAME
FROM CDB_DATA_FILES
ORDER BY CON_ID, TABLESPACE_NAME;


--Oracle에서는 CON_ID를 숫자로 가정하지 말고 실제 PDB 목록을 먼저 확인
SELECT CON_ID, NAME, OPEN_MODE
FROM V$PDBS
ORDER BY CON_ID;

-- PDB$SEED의 실제 CON_ID를 확인한 뒤 조회
SELECT CON_ID, FILE_NAME, TABLESPACE_NAME
FROM CDB_DATA_FILES
ORDER BY CON_ID, FILE_NAME;

SELECT CON_ID, NAME
FROM V$DATAFILE
ORDER BY CON_ID, NAME;

-- movie_db를 생성하고 joy 계정으로 권한 부여
CREATE PLUGGABLE DATABASE movie_db
ADMIN USER joy
IDENTIFIED BY Joy1234
ROLES = (DBA)
FILE_NAME_CONVERT = (
    '/opt/oracle/oradata/FREE/pdbseed/',
    '/opt/oracle/oradata/FREE/movie_db/'
);

-- 현재 Oracle 인스턴스에 존재하는 PDB(Pluggable Database) 목록과 상태를 조회
SELECT CON_ID, NAME, OPEN_MODE
FROM V$PDBS;


-- movie_db 생성에 필요한 정확한 경로 확인
SELECT CON_ID, NAME
FROM V$DATAFILE
ORDER BY CON_ID, NAME;

-- movie_db 쓰기권한 부여
-- username : sys, password: Oracle1234, Role: SYSDBA

-- 현재 컨테이너 확인
SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS CON_NAME
FROM DUAL;

-- movie_db read/write 권한으로 변경
ALTER PLUGGABLE DATABASE movie_db OPEN READ WRITE;


-- 상태 확인
SELECT CON_ID, NAME, OPEN_MODE
FROM V$PDBS
WHERE NAME = 'MOVIE_DB';