-- 1. JOY 기본 테이블스페이스
SELECT USERNAME, DEFAULT_TABLESPACE
FROM DBA_USERS
WHERE USERNAME = 'JOY';

-- 2. MEMBER 테이블 위치
SELECT TABLE_NAME, TABLESPACE_NAME
FROM USER_TABLES
WHERE TABLE_NAME = 'MEMBER';

-- 3. MEMBER 인덱스 위치
SELECT INDEX_NAME, TABLESPACE_NAME
FROM USER_INDEXES
WHERE TABLE_NAME = 'MEMBER';


SELECT SYS_CONTEXT('USERENV', 'CON_NAME')
FROM DUAL;

SELECT USER
FROM DUAL;


CREATE TABLE MEMBER (
    MEMBER_ID      NUMBER          CONSTRAINT PK_MEMBER PRIMARY KEY,
    MEMBER_NAME    VARCHAR2(50)    NOT NULL,
    EMAIL          VARCHAR2(100)   CONSTRAINT UQ_MEMBER_EMAIL UNIQUE,
    GRADE          VARCHAR2(10)    DEFAULT 'BASIC',
    JOIN_DATE      DATE            DEFAULT SYSDATE,

    CONSTRAINT CK_MEMBER_GRADE
        CHECK (GRADE IN ('BASIC', 'VIP', 'VVIP'))
)
TABLESPACE USERS;

-- 데이터 생성
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, EMAIL, GRADE)
VALUES (1, '홍길동', 'hong@example.com', 'BASIC');

INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, EMAIL, GRADE)
VALUES (2, '김철수', 'kim@example.com', 'VIP');

INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, EMAIL, GRADE)
VALUES (3, '이영희', 'lee@example.com', 'VVIP');

INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, EMAIL, GRADE)
VALUES (4, '박민수', 'park@example.com', 'BASIC');

INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, EMAIL, GRADE)
VALUES (5, '최수진', 'choi@example.com', 'VIP');

COMMIT;